### ISSUE TITLE
Change `app.RunTailwind("tailwind", "./");` to `_ = app.RunTailwind("tailwind", "./");`

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [Practical-ASP-NET/Tailwind.Extensions.AspNetCore#4]
First: thank you for making this plugin, it makes my life a lot easier.

The issue is about changing `app.RunTailwind("tailwind", "./");` to `_ = app.RunTailwind("tailwind", "./");` in the documentation. This makes sure that the C# linter understands that the Task is discarded and not awaited. It also makes sure that people don't add an await because they think it is a type (like me).

**Comment by jonhilt** [comment]
Thanks for this!

I've been experimenting with using a hosted service to handle this instead of the current method. This could be a better way to run this in the background when the app starts.

But in the meantime I've updated the readme to cover using the discard parameter.

Thanks for flagging this up.
